version: '3'
services: 
  nginx: 
    restart: always
    build: 
      context: ./nginx
      dockerfile: Dockerfile.dev
      # make sure this always restarts 
      #nginx default 80
    ports: 
      - "3050:80"
  postgres: 
    image: 'postgres:latest'
  redis:
    image: 'redis:latest'
  api:
    build: 
      context: ./server
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      #name of service defined above
      - REDIS_HOST=redis
      #found in redis dockerhub docs
      - REDIS_PORT=6379
      - PGUSER=postgres
      # defined in service name
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./client:/app
  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile.dev
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - /app/node_modules
      - ./worker:/app
    